name: Run Python Script

# Este workflow se ejecutará cuando haya un push en la rama `main`
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Se ejecutará en un entorno de Ubuntu, pero puedes cambiarlo si prefieres otro SO.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Esto descarga el código fuente de tu repositorio.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Asegúrate de usar la versión que corresponde con tu proyecto.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Actualiza pip
        pip install -r requirements.txt  # Instala las dependencias definidas en requirements.txt

    - name: Run Python Script
      run: python transaction_script.py  # Ejecuta el script Python

    - name: Run Shell Script
      run: bash run.sh  # Si tienes un script adicional en Bash
